### ISSUE TITLE
Python-3.9 support

### ISSUE THREAD

**Issue by stonebig** [altendky/pyqt-tools#59]
Would it be also possible to get a Python-3.9 wheel for Windows 10 64 bit ?

If you need space on pypi, I would suggest that maybe old 32bit wheels may have to go

**Comment by altendky** [comment]
I'll keep this open until the wheels actually get to PyPI but they are presently available for download at https://github.com/altendky/pyqt5-tools/actions/runs/300796583 (if you are logged in).

**Comment by altendky** [comment]
@Admund20 wrote:
> so what should I do? I really need to install pyqt5-tools.

Let's start by moving to the right ticket.  you can get the wheels at the link above and install the files after you download them.  Why is 3.9 so mandatory?  But sure, I've been getting probably four hours a day working on the restructure since I hit the limit.

**Comment by Admund20** [comment]
Ok, thank you so much. I just downloaded the wheel version that fits my specs. Do I install the wheel in a certain directory or anywhere in the computer? Thank you again.

**Comment by Admund20** [comment]
To answer your question about 3.9 version, this was the latest out there and I'm a complete beginner hence I downloaded it. :-))

**Comment by altendky** [comment]
@Admund20, you would run `pip` in the same was as you would if installing a package normally except you would specify the path to the wheel instead of just `pyqt5-tools`.  If it's in the current directory you prefix a `./` like `pip install ./pyqt5_tools-whatever.whl`.  It is more or less always good to work in a virtual environment and only run pip from an env.

https://chriswarrick.com/blog/2018/09/04/python-virtual-environments/

Also, while the obvious choice is to use the latest (3.9) sometimes packages don't quite keep up (sorry) and running one version before (latest 3.8) works out a bit more smoothly.  3.9 has only been out a couple weeks if I remember correctly.  `:]`

If you want some more interactive help there's `#python` on freenode IRC.  I'm there a lot so this isn't meant to try to dump your queries on someone else.

https://www.python.org/community/irc/

**Comment by Admund20** [comment]
ok, thank you.

**Comment by amal-khailtash** [comment]
I am seeing this in latest python 3.9 version.  I assume it is related to the fact that there is no wheel package for this version yet:

```
$ pip --version
pip 20.2.4 from .venv/lib/python3.9/site-packages/pip (python 3.9)

$ pip install -U pyqt5-tools
ERROR: Could not find a version that satisfies the requirement pyqt5-tools (from versions: none)
ERROR: No matching distribution found for pyqt5-tools

```

**Comment by altendky** [comment]
@amal-khailtash, yes.  You can manually download as mentioned above, use Python 3.8, or wait.  `:|`  I'm getting 'close' with the package split up but not there yet.

**Comment by stonebig** [comment]
the one on https://github.com/altendky/pyqt5-tools/actions/runs/300796583 works, if you're in a hurry.

**Comment by amal-khailtash** [comment]
That's great.  It can wait :)

**Comment by altendky** [comment]
New v2 is finally out with 3.9 support.  Broken up with help from https://github.com/altendky/pyqt-plugins and https://github.com/altendky/qt-applications.
